_format_version: "3.0"
_transform: true

services:
  - name: terrascore-api
    url: http://host.docker.internal:8080
    routes:
      - name: api-v1
        paths:
          - /v1
        strip_path: false
        protocols:
          - http
      - name: health
        paths:
          - /health
        strip_path: false
        protocols:
          - http

  - name: keycloak
    url: http://keycloak:8180
    routes:
      - name: keycloak-auth
        paths:
          - /auth
        strip_path: false
        protocols:
          - http

plugins:
  - name: cors
    service: terrascore-api
    config:
      origins:
        - "http://localhost:3000"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - X-Request-ID
      exposed_headers:
        - X-Request-ID
      credentials: true
      max_age: 3600

  - name: rate-limiting
    service: terrascore-api
    config:
      minute: 60
      policy: local
      fault_tolerant: true
      hide_client_headers: false

  - name: request-size-limiting
    service: terrascore-api
    config:
      allowed_payload_size: 10
      size_unit: megabytes
