// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAgents = `-- name: CountAgents :one
SELECT count(*) FROM agents
`

func (q *Queries) CountAgents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAgents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (full_name, phone, email, date_of_birth, home_location, state_code, district_code, keycloak_id)
VALUES ($1, $2, $3, $4, ST_SetSRID(ST_MakePoint($5, $6), 4326), $7, $8, $9)
RETURNING id, full_name, phone, email, date_of_birth, aadhaar_hash, aadhaar_verified, home_location, last_known_location, last_location_at, preferred_radius_km, state_code, district_code, status, tier, vehicle_type, total_jobs_completed, avg_rating, completion_rate, qa_pass_rate, last_job_completed_at, bank_account_enc, bank_ifsc, upi_id, wallet_balance, certifications, fcm_token, device_id, app_version, is_online, available_days, available_start, available_end, keycloak_id, created_at, updated_at
`

type CreateAgentParams struct {
	FullName      string      `json:"full_name"`
	Phone         string      `json:"phone"`
	Email         *string     `json:"email"`
	DateOfBirth   pgtype.Date `json:"date_of_birth"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	StateCode     *string     `json:"state_code"`
	DistrictCode  *string     `json:"district_code"`
	KeycloakID    *string     `json:"keycloak_id"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.DateOfBirth,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.StateCode,
		arg.DistrictCode,
		arg.KeycloakID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.DateOfBirth,
		&i.AadhaarHash,
		&i.AadhaarVerified,
		&i.HomeLocation,
		&i.LastKnownLocation,
		&i.LastLocationAt,
		&i.PreferredRadiusKm,
		&i.StateCode,
		&i.DistrictCode,
		&i.Status,
		&i.Tier,
		&i.VehicleType,
		&i.TotalJobsCompleted,
		&i.AvgRating,
		&i.CompletionRate,
		&i.QaPassRate,
		&i.LastJobCompletedAt,
		&i.BankAccountEnc,
		&i.BankIfsc,
		&i.UpiID,
		&i.WalletBalance,
		&i.Certifications,
		&i.FcmToken,
		&i.DeviceID,
		&i.AppVersion,
		&i.IsOnline,
		&i.AvailableDays,
		&i.AvailableStart,
		&i.AvailableEnd,
		&i.KeycloakID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findNearbyAgents = `-- name: FindNearbyAgents :many
SELECT id, full_name, phone, email, date_of_birth, aadhaar_hash, aadhaar_verified, home_location, last_known_location, last_location_at, preferred_radius_km, state_code, district_code, status, tier, vehicle_type, total_jobs_completed, avg_rating, completion_rate, qa_pass_rate, last_job_completed_at, bank_account_enc, bank_ifsc, upi_id, wallet_balance, certifications, fcm_token, device_id, app_version, is_online, available_days, available_start, available_end, keycloak_id, created_at, updated_at,
    ST_Distance(last_known_location::geography, ST_SetSRID(ST_MakePoint($1, $2), 4326)::geography) / 1000 AS distance_km
FROM agents
WHERE status = 'active'
    AND is_online = TRUE
    AND ST_DWithin(
        last_known_location::geography,
        ST_SetSRID(ST_MakePoint($1, $2), 4326)::geography,
        $3
    )
ORDER BY distance_km ASC
LIMIT $4
`

type FindNearbyAgentsParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	StDwithin     interface{} `json:"st_dwithin"`
	Limit         int32       `json:"limit"`
}

type FindNearbyAgentsRow struct {
	ID                 uuid.UUID          `json:"id"`
	FullName           string             `json:"full_name"`
	Phone              string             `json:"phone"`
	Email              *string            `json:"email"`
	DateOfBirth        pgtype.Date        `json:"date_of_birth"`
	AadhaarHash        *string            `json:"aadhaar_hash"`
	AadhaarVerified    *bool              `json:"aadhaar_verified"`
	HomeLocation       interface{}        `json:"home_location"`
	LastKnownLocation  interface{}        `json:"last_known_location"`
	LastLocationAt     pgtype.Timestamptz `json:"last_location_at"`
	PreferredRadiusKm  *int32             `json:"preferred_radius_km"`
	StateCode          *string            `json:"state_code"`
	DistrictCode       *string            `json:"district_code"`
	Status             *string            `json:"status"`
	Tier               *string            `json:"tier"`
	VehicleType        *string            `json:"vehicle_type"`
	TotalJobsCompleted *int32             `json:"total_jobs_completed"`
	AvgRating          pgtype.Numeric     `json:"avg_rating"`
	CompletionRate     pgtype.Numeric     `json:"completion_rate"`
	QaPassRate         pgtype.Numeric     `json:"qa_pass_rate"`
	LastJobCompletedAt pgtype.Timestamptz `json:"last_job_completed_at"`
	BankAccountEnc     *string            `json:"bank_account_enc"`
	BankIfsc           *string            `json:"bank_ifsc"`
	UpiID              *string            `json:"upi_id"`
	WalletBalance      pgtype.Numeric     `json:"wallet_balance"`
	Certifications     []string           `json:"certifications"`
	FcmToken           *string            `json:"fcm_token"`
	DeviceID           *string            `json:"device_id"`
	AppVersion         *string            `json:"app_version"`
	IsOnline           *bool              `json:"is_online"`
	AvailableDays      []string           `json:"available_days"`
	AvailableStart     pgtype.Time        `json:"available_start"`
	AvailableEnd       pgtype.Time        `json:"available_end"`
	KeycloakID         *string            `json:"keycloak_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DistanceKm         int32              `json:"distance_km"`
}

func (q *Queries) FindNearbyAgents(ctx context.Context, arg FindNearbyAgentsParams) ([]FindNearbyAgentsRow, error) {
	rows, err := q.db.Query(ctx, findNearbyAgents,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.StDwithin,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindNearbyAgentsRow{}
	for rows.Next() {
		var i FindNearbyAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.DateOfBirth,
			&i.AadhaarHash,
			&i.AadhaarVerified,
			&i.HomeLocation,
			&i.LastKnownLocation,
			&i.LastLocationAt,
			&i.PreferredRadiusKm,
			&i.StateCode,
			&i.DistrictCode,
			&i.Status,
			&i.Tier,
			&i.VehicleType,
			&i.TotalJobsCompleted,
			&i.AvgRating,
			&i.CompletionRate,
			&i.QaPassRate,
			&i.LastJobCompletedAt,
			&i.BankAccountEnc,
			&i.BankIfsc,
			&i.UpiID,
			&i.WalletBalance,
			&i.Certifications,
			&i.FcmToken,
			&i.DeviceID,
			&i.AppVersion,
			&i.IsOnline,
			&i.AvailableDays,
			&i.AvailableStart,
			&i.AvailableEnd,
			&i.KeycloakID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DistanceKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, full_name, phone, email, date_of_birth, aadhaar_hash, aadhaar_verified, home_location, last_known_location, last_location_at, preferred_radius_km, state_code, district_code, status, tier, vehicle_type, total_jobs_completed, avg_rating, completion_rate, qa_pass_rate, last_job_completed_at, bank_account_enc, bank_ifsc, upi_id, wallet_balance, certifications, fcm_token, device_id, app_version, is_online, available_days, available_start, available_end, keycloak_id, created_at, updated_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.DateOfBirth,
		&i.AadhaarHash,
		&i.AadhaarVerified,
		&i.HomeLocation,
		&i.LastKnownLocation,
		&i.LastLocationAt,
		&i.PreferredRadiusKm,
		&i.StateCode,
		&i.DistrictCode,
		&i.Status,
		&i.Tier,
		&i.VehicleType,
		&i.TotalJobsCompleted,
		&i.AvgRating,
		&i.CompletionRate,
		&i.QaPassRate,
		&i.LastJobCompletedAt,
		&i.BankAccountEnc,
		&i.BankIfsc,
		&i.UpiID,
		&i.WalletBalance,
		&i.Certifications,
		&i.FcmToken,
		&i.DeviceID,
		&i.AppVersion,
		&i.IsOnline,
		&i.AvailableDays,
		&i.AvailableStart,
		&i.AvailableEnd,
		&i.KeycloakID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByKeycloakID = `-- name: GetAgentByKeycloakID :one
SELECT id, full_name, phone, email, date_of_birth, aadhaar_hash, aadhaar_verified, home_location, last_known_location, last_location_at, preferred_radius_km, state_code, district_code, status, tier, vehicle_type, total_jobs_completed, avg_rating, completion_rate, qa_pass_rate, last_job_completed_at, bank_account_enc, bank_ifsc, upi_id, wallet_balance, certifications, fcm_token, device_id, app_version, is_online, available_days, available_start, available_end, keycloak_id, created_at, updated_at FROM agents WHERE keycloak_id = $1
`

func (q *Queries) GetAgentByKeycloakID(ctx context.Context, keycloakID *string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByKeycloakID, keycloakID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.DateOfBirth,
		&i.AadhaarHash,
		&i.AadhaarVerified,
		&i.HomeLocation,
		&i.LastKnownLocation,
		&i.LastLocationAt,
		&i.PreferredRadiusKm,
		&i.StateCode,
		&i.DistrictCode,
		&i.Status,
		&i.Tier,
		&i.VehicleType,
		&i.TotalJobsCompleted,
		&i.AvgRating,
		&i.CompletionRate,
		&i.QaPassRate,
		&i.LastJobCompletedAt,
		&i.BankAccountEnc,
		&i.BankIfsc,
		&i.UpiID,
		&i.WalletBalance,
		&i.Certifications,
		&i.FcmToken,
		&i.DeviceID,
		&i.AppVersion,
		&i.IsOnline,
		&i.AvailableDays,
		&i.AvailableStart,
		&i.AvailableEnd,
		&i.KeycloakID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByPhone = `-- name: GetAgentByPhone :one
SELECT id, full_name, phone, email, date_of_birth, aadhaar_hash, aadhaar_verified, home_location, last_known_location, last_location_at, preferred_radius_km, state_code, district_code, status, tier, vehicle_type, total_jobs_completed, avg_rating, completion_rate, qa_pass_rate, last_job_completed_at, bank_account_enc, bank_ifsc, upi_id, wallet_balance, certifications, fcm_token, device_id, app_version, is_online, available_days, available_start, available_end, keycloak_id, created_at, updated_at FROM agents WHERE phone = $1
`

func (q *Queries) GetAgentByPhone(ctx context.Context, phone string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByPhone, phone)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.DateOfBirth,
		&i.AadhaarHash,
		&i.AadhaarVerified,
		&i.HomeLocation,
		&i.LastKnownLocation,
		&i.LastLocationAt,
		&i.PreferredRadiusKm,
		&i.StateCode,
		&i.DistrictCode,
		&i.Status,
		&i.Tier,
		&i.VehicleType,
		&i.TotalJobsCompleted,
		&i.AvgRating,
		&i.CompletionRate,
		&i.QaPassRate,
		&i.LastJobCompletedAt,
		&i.BankAccountEnc,
		&i.BankIfsc,
		&i.UpiID,
		&i.WalletBalance,
		&i.Certifications,
		&i.FcmToken,
		&i.DeviceID,
		&i.AppVersion,
		&i.IsOnline,
		&i.AvailableDays,
		&i.AvailableStart,
		&i.AvailableEnd,
		&i.KeycloakID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, full_name, phone, email, date_of_birth, aadhaar_hash, aadhaar_verified, home_location, last_known_location, last_location_at, preferred_radius_km, state_code, district_code, status, tier, vehicle_type, total_jobs_completed, avg_rating, completion_rate, qa_pass_rate, last_job_completed_at, bank_account_enc, bank_ifsc, upi_id, wallet_balance, certifications, fcm_token, device_id, app_version, is_online, available_days, available_start, available_end, keycloak_id, created_at, updated_at FROM agents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAgentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.DateOfBirth,
			&i.AadhaarHash,
			&i.AadhaarVerified,
			&i.HomeLocation,
			&i.LastKnownLocation,
			&i.LastLocationAt,
			&i.PreferredRadiusKm,
			&i.StateCode,
			&i.DistrictCode,
			&i.Status,
			&i.Tier,
			&i.VehicleType,
			&i.TotalJobsCompleted,
			&i.AvgRating,
			&i.CompletionRate,
			&i.QaPassRate,
			&i.LastJobCompletedAt,
			&i.BankAccountEnc,
			&i.BankIfsc,
			&i.UpiID,
			&i.WalletBalance,
			&i.Certifications,
			&i.FcmToken,
			&i.DeviceID,
			&i.AppVersion,
			&i.IsOnline,
			&i.AvailableDays,
			&i.AvailableStart,
			&i.AvailableEnd,
			&i.KeycloakID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentFCMToken = `-- name: UpdateAgentFCMToken :exec
UPDATE agents SET fcm_token = $2, device_id = $3, app_version = $4, updated_at = NOW() WHERE id = $1
`

type UpdateAgentFCMTokenParams struct {
	ID         uuid.UUID `json:"id"`
	FcmToken   *string   `json:"fcm_token"`
	DeviceID   *string   `json:"device_id"`
	AppVersion *string   `json:"app_version"`
}

func (q *Queries) UpdateAgentFCMToken(ctx context.Context, arg UpdateAgentFCMTokenParams) error {
	_, err := q.db.Exec(ctx, updateAgentFCMToken,
		arg.ID,
		arg.FcmToken,
		arg.DeviceID,
		arg.AppVersion,
	)
	return err
}

const updateAgentLocation = `-- name: UpdateAgentLocation :exec
UPDATE agents SET
    last_known_location = ST_SetSRID(ST_MakePoint($2, $3), 4326),
    last_location_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdateAgentLocationParams struct {
	ID            uuid.UUID   `json:"id"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
}

func (q *Queries) UpdateAgentLocation(ctx context.Context, arg UpdateAgentLocationParams) error {
	_, err := q.db.Exec(ctx, updateAgentLocation, arg.ID, arg.StMakepoint, arg.StMakepoint_2)
	return err
}

const updateAgentOnlineStatus = `-- name: UpdateAgentOnlineStatus :exec
UPDATE agents SET is_online = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAgentOnlineStatusParams struct {
	ID       uuid.UUID `json:"id"`
	IsOnline *bool     `json:"is_online"`
}

func (q *Queries) UpdateAgentOnlineStatus(ctx context.Context, arg UpdateAgentOnlineStatusParams) error {
	_, err := q.db.Exec(ctx, updateAgentOnlineStatus, arg.ID, arg.IsOnline)
	return err
}

const updateAgentProfile = `-- name: UpdateAgentProfile :exec
UPDATE agents SET
    full_name = COALESCE($2, full_name),
    email = COALESCE($3, email),
    vehicle_type = COALESCE($4, vehicle_type),
    preferred_radius_km = COALESCE($5, preferred_radius_km),
    bank_account_enc = COALESCE($6, bank_account_enc),
    bank_ifsc = COALESCE($7, bank_ifsc),
    upi_id = COALESCE($8, upi_id),
    available_days = COALESCE($9, available_days),
    available_start = COALESCE($10, available_start),
    available_end = COALESCE($11, available_end),
    updated_at = NOW()
WHERE id = $1
`

type UpdateAgentProfileParams struct {
	ID                uuid.UUID   `json:"id"`
	FullName          string      `json:"full_name"`
	Email             *string     `json:"email"`
	VehicleType       *string     `json:"vehicle_type"`
	PreferredRadiusKm *int32      `json:"preferred_radius_km"`
	BankAccountEnc    *string     `json:"bank_account_enc"`
	BankIfsc          *string     `json:"bank_ifsc"`
	UpiID             *string     `json:"upi_id"`
	AvailableDays     []string    `json:"available_days"`
	AvailableStart    pgtype.Time `json:"available_start"`
	AvailableEnd      pgtype.Time `json:"available_end"`
}

func (q *Queries) UpdateAgentProfile(ctx context.Context, arg UpdateAgentProfileParams) error {
	_, err := q.db.Exec(ctx, updateAgentProfile,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.VehicleType,
		arg.PreferredRadiusKm,
		arg.BankAccountEnc,
		arg.BankIfsc,
		arg.UpiID,
		arg.AvailableDays,
		arg.AvailableStart,
		arg.AvailableEnd,
	)
	return err
}

const updateAgentStats = `-- name: UpdateAgentStats :exec
UPDATE agents SET
    total_jobs_completed = $2,
    avg_rating = $3,
    completion_rate = $4,
    qa_pass_rate = $5,
    last_job_completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdateAgentStatsParams struct {
	ID                 uuid.UUID      `json:"id"`
	TotalJobsCompleted *int32         `json:"total_jobs_completed"`
	AvgRating          pgtype.Numeric `json:"avg_rating"`
	CompletionRate     pgtype.Numeric `json:"completion_rate"`
	QaPassRate         pgtype.Numeric `json:"qa_pass_rate"`
}

func (q *Queries) UpdateAgentStats(ctx context.Context, arg UpdateAgentStatsParams) error {
	_, err := q.db.Exec(ctx, updateAgentStats,
		arg.ID,
		arg.TotalJobsCompleted,
		arg.AvgRating,
		arg.CompletionRate,
		arg.QaPassRate,
	)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE agents SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAgentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status *string   `json:"status"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAgentStatus, arg.ID, arg.Status)
	return err
}
