// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUnreadAlerts = `-- name: CountUnreadAlerts :one
SELECT count(*) FROM alerts WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadAlerts(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadAlerts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (user_id, type, title, body, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, data, is_read, created_at
`

type CreateAlertParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
	Title  string    `json:"title"`
	Body   *string   `json:"body"`
	Data   []byte    `json:"data"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listAlertsByUser = `-- name: ListAlertsByUser :many
SELECT id, user_id, type, title, body, data, is_read, created_at FROM alerts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListAlertsByUser(ctx context.Context, arg ListAlertsByUserParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertRead = `-- name: MarkAlertRead :exec
UPDATE alerts SET is_read = TRUE WHERE id = $1
`

func (q *Queries) MarkAlertRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAlertRead, id)
	return err
}

const markAllAlertsRead = `-- name: MarkAllAlertsRead :exec
UPDATE alerts SET is_read = TRUE WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllAlertsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllAlertsRead, userID)
	return err
}
