// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                 uuid.UUID          `json:"id"`
	FullName           string             `json:"full_name"`
	Phone              string             `json:"phone"`
	Email              *string            `json:"email"`
	DateOfBirth        pgtype.Date        `json:"date_of_birth"`
	AadhaarHash        *string            `json:"aadhaar_hash"`
	AadhaarVerified    *bool              `json:"aadhaar_verified"`
	HomeLocation       interface{}        `json:"home_location"`
	LastKnownLocation  interface{}        `json:"last_known_location"`
	LastLocationAt     pgtype.Timestamptz `json:"last_location_at"`
	PreferredRadiusKm  *int32             `json:"preferred_radius_km"`
	StateCode          *string            `json:"state_code"`
	DistrictCode       *string            `json:"district_code"`
	Status             *string            `json:"status"`
	Tier               *string            `json:"tier"`
	VehicleType        *string            `json:"vehicle_type"`
	TotalJobsCompleted *int32             `json:"total_jobs_completed"`
	AvgRating          pgtype.Numeric     `json:"avg_rating"`
	CompletionRate     pgtype.Numeric     `json:"completion_rate"`
	QaPassRate         pgtype.Numeric     `json:"qa_pass_rate"`
	LastJobCompletedAt pgtype.Timestamptz `json:"last_job_completed_at"`
	BankAccountEnc     *string            `json:"bank_account_enc"`
	BankIfsc           *string            `json:"bank_ifsc"`
	UpiID              *string            `json:"upi_id"`
	WalletBalance      pgtype.Numeric     `json:"wallet_balance"`
	Certifications     []string           `json:"certifications"`
	FcmToken           *string            `json:"fcm_token"`
	DeviceID           *string            `json:"device_id"`
	AppVersion         *string            `json:"app_version"`
	IsOnline           *bool              `json:"is_online"`
	AvailableDays      []string           `json:"available_days"`
	AvailableStart     pgtype.Time        `json:"available_start"`
	AvailableEnd       pgtype.Time        `json:"available_end"`
	KeycloakID         *string            `json:"keycloak_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AgentPayout struct {
	ID                 uuid.UUID          `json:"id"`
	AgentID            uuid.UUID          `json:"agent_id"`
	PeriodStart        pgtype.Date        `json:"period_start"`
	PeriodEnd          pgtype.Date        `json:"period_end"`
	TotalJobs          *int32             `json:"total_jobs"`
	GrossAmount        pgtype.Numeric     `json:"gross_amount"`
	PlatformCommission pgtype.Numeric     `json:"platform_commission"`
	TdsDeducted        pgtype.Numeric     `json:"tds_deducted"`
	NetAmount          pgtype.Numeric     `json:"net_amount"`
	Status             *string            `json:"status"`
	RazorpayPayoutID   *string            `json:"razorpay_payout_id"`
	FailureReason      *string            `json:"failure_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Alert struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      *string            `json:"body"`
	Data      []byte             `json:"data"`
	IsRead    *bool              `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AnalyticsEvent struct {
	ID         int64              `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	EventType  string             `json:"event_type"`
	Properties []byte             `json:"properties"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ChecklistTemplate struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	SurveyType string             `json:"survey_type"`
	Version    *int32             `json:"version"`
	IsActive   *bool              `json:"is_active"`
	Steps      json.RawMessage    `json:"steps"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type JobOffer struct {
	ID            uuid.UUID          `json:"id"`
	JobID         uuid.UUID          `json:"job_id"`
	AgentID       uuid.UUID          `json:"agent_id"`
	CascadeRound  int32              `json:"cascade_round"`
	OfferRank     int32              `json:"offer_rank"`
	DistanceKm    *float32           `json:"distance_km"`
	MatchScore    pgtype.Numeric     `json:"match_score"`
	Status        *string            `json:"status"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	RespondedAt   pgtype.Timestamptz `json:"responded_at"`
	ExpiresAt     time.Time          `json:"expires_at"`
	DeclineReason *string            `json:"decline_reason"`
}

type Parcel struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Label             *string            `json:"label"`
	SurveyNumber      *string            `json:"survey_number"`
	Village           *string            `json:"village"`
	Taluk             *string            `json:"taluk"`
	District          string             `json:"district"`
	State             string             `json:"state"`
	StateCode         string             `json:"state_code"`
	PinCode           *string            `json:"pin_code"`
	Boundary          string             `json:"boundary"`
	Centroid          interface{}        `json:"centroid"`
	AreaSqm           *float32           `json:"area_sqm"`
	LandType          *string            `json:"land_type"`
	RegisteredAreaSqm *float32           `json:"registered_area_sqm"`
	TitleDeedS3Key    *string            `json:"title_deed_s3_key"`
	Status            *string            `json:"status"`
	MonitoringSince   pgtype.Timestamptz `json:"monitoring_since"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RiskScore struct {
	ID                  uuid.UUID          `json:"id"`
	ParcelID            uuid.UUID          `json:"parcel_id"`
	JobID               pgtype.UUID        `json:"job_id"`
	OverallScore        pgtype.Numeric     `json:"overall_score"`
	RiskLevel           string             `json:"risk_level"`
	EncroachmentScore   pgtype.Numeric     `json:"encroachment_score"`
	BoundaryScore       pgtype.Numeric     `json:"boundary_score"`
	EnvironmentalScore  pgtype.Numeric     `json:"environmental_score"`
	NeighborhoodScore   pgtype.Numeric     `json:"neighborhood_score"`
	ContributingFactors []byte             `json:"contributing_factors"`
	ComputedAt          pgtype.Timestamptz `json:"computed_at"`
}

type Subscription struct {
	ID                      uuid.UUID          `json:"id"`
	UserID                  uuid.UUID          `json:"user_id"`
	ParcelID                uuid.UUID          `json:"parcel_id"`
	Plan                    string             `json:"plan"`
	Status                  *string            `json:"status"`
	AmountPerCycle          pgtype.Numeric     `json:"amount_per_cycle"`
	RazorpaySubscriptionID  *string            `json:"razorpay_subscription_id"`
	CurrentPeriodStart      pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd        pgtype.Timestamptz `json:"current_period_end"`
	VisitsUsedThisPeriod    *int32             `json:"visits_used_this_period"`
	OnDemandVisitsRemaining *int32             `json:"on_demand_visits_remaining"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type SurveyJob struct {
	ID                uuid.UUID          `json:"id"`
	ParcelID          uuid.UUID          `json:"parcel_id"`
	SubscriptionID    pgtype.UUID        `json:"subscription_id"`
	UserID            uuid.UUID          `json:"user_id"`
	SurveyType        string             `json:"survey_type"`
	Priority          *string            `json:"priority"`
	Deadline          time.Time          `json:"deadline"`
	Trigger           *string            `json:"trigger"`
	Status            *string            `json:"status"`
	AssignedAgentID   pgtype.UUID        `json:"assigned_agent_id"`
	AssignedAt        pgtype.Timestamptz `json:"assigned_at"`
	CascadeRound      *int32             `json:"cascade_round"`
	TotalOffersSent   *int32             `json:"total_offers_sent"`
	AgentArrivedAt    pgtype.Timestamptz `json:"agent_arrived_at"`
	SurveyStartedAt   pgtype.Timestamptz `json:"survey_started_at"`
	SurveySubmittedAt pgtype.Timestamptz `json:"survey_submitted_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ArrivalLocation   interface{}        `json:"arrival_location"`
	ArrivalDistanceM  *float32           `json:"arrival_distance_m"`
	BasePayout        pgtype.Numeric     `json:"base_payout"`
	DistanceBonus     pgtype.Numeric     `json:"distance_bonus"`
	UrgencyBonus      pgtype.Numeric     `json:"urgency_bonus"`
	TotalPayout       pgtype.Numeric     `json:"total_payout"`
	PayoutStatus      *string            `json:"payout_status"`
	LandownerRating   pgtype.Numeric     `json:"landowner_rating"`
	QaScore           pgtype.Numeric     `json:"qa_score"`
	QaStatus          *string            `json:"qa_status"`
	QaNotes           *string            `json:"qa_notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type SurveyMedium struct {
	ID             uuid.UUID          `json:"id"`
	JobID          uuid.UUID          `json:"job_id"`
	AgentID        uuid.UUID          `json:"agent_id"`
	StepID         string             `json:"step_id"`
	MediaType      string             `json:"media_type"`
	S3Key          string             `json:"s3_key"`
	FileSizeBytes  *int64             `json:"file_size_bytes"`
	DurationSec    *int32             `json:"duration_sec"`
	Location       string             `json:"location"`
	CapturedAt     time.Time          `json:"captured_at"`
	FileHashSha256 string             `json:"file_hash_sha256"`
	DeviceID       *string            `json:"device_id"`
	WithinBoundary *bool              `json:"within_boundary"`
	DuplicateHash  *string            `json:"duplicate_hash"`
	UploadedAt     pgtype.Timestamptz `json:"uploaded_at"`
}

type SurveyResponse struct {
	ID              uuid.UUID          `json:"id"`
	JobID           uuid.UUID          `json:"job_id"`
	AgentID         uuid.UUID          `json:"agent_id"`
	TemplateID      pgtype.UUID        `json:"template_id"`
	Responses       json.RawMessage    `json:"responses"`
	GpsTrail        interface{}        `json:"gps_trail"`
	DeviceInfo      []byte             `json:"device_info"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	DurationMinutes *float32           `json:"duration_minutes"`
}

type TaskQueue struct {
	ID           int64              `json:"id"`
	TaskType     string             `json:"task_type"`
	Payload      json.RawMessage    `json:"payload"`
	Status       *string            `json:"status"`
	Priority     *int32             `json:"priority"`
	Attempts     *int32             `json:"attempts"`
	MaxAttempts  *int32             `json:"max_attempts"`
	LastError    *string            `json:"last_error"`
	ErrorMessage *string            `json:"error_message"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	SubscriptionID    pgtype.UUID        `json:"subscription_id"`
	Type              string             `json:"type"`
	Amount            pgtype.Numeric     `json:"amount"`
	Status            *string            `json:"status"`
	RazorpayPaymentID *string            `json:"razorpay_payment_id"`
	RazorpayOrderID   *string            `json:"razorpay_order_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	Phone             string             `json:"phone"`
	Email             *string            `json:"email"`
	FullName          string             `json:"full_name"`
	Role              string             `json:"role"`
	AvatarUrl         *string            `json:"avatar_url"`
	StateCode         *string            `json:"state_code"`
	DistrictCode      *string            `json:"district_code"`
	City              *string            `json:"city"`
	Status            *string            `json:"status"`
	PhoneVerified     *bool              `json:"phone_verified"`
	Language          *string            `json:"language"`
	NotificationPrefs []byte             `json:"notification_prefs"`
	KeycloakID        *string            `json:"keycloak_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
