// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countReportsByParcel = `-- name: CountReportsByParcel :one
SELECT count(*) FROM reports WHERE parcel_id = $1
`

func (q *Queries) CountReportsByParcel(ctx context.Context, parcelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByParcel, parcelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (parcel_id, job_id, s3_key, report_type, format, generated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, parcel_id, job_id, s3_key, report_type, format, generated_at, created_at
`

type CreateReportParams struct {
	ParcelID   uuid.UUID `json:"parcel_id"`
	JobID      uuid.UUID `json:"job_id"`
	S3Key      string    `json:"s3_key"`
	ReportType string    `json:"report_type"`
	Format     string    `json:"format"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ParcelID,
		arg.JobID,
		arg.S3Key,
		arg.ReportType,
		arg.Format,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ParcelID,
		&i.JobID,
		&i.S3Key,
		&i.ReportType,
		&i.Format,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, parcel_id, job_id, s3_key, report_type, format, generated_at, created_at FROM reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ParcelID,
		&i.JobID,
		&i.S3Key,
		&i.ReportType,
		&i.Format,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listReportsByParcel = `-- name: ListReportsByParcel :many
SELECT id, parcel_id, job_id, s3_key, report_type, format, generated_at, created_at FROM reports
WHERE parcel_id = $1
ORDER BY generated_at DESC
LIMIT $2 OFFSET $3
`

type ListReportsByParcelParams struct {
	ParcelID uuid.UUID `json:"parcel_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListReportsByParcel(ctx context.Context, arg ListReportsByParcelParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByParcel, arg.ParcelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ParcelID,
			&i.JobID,
			&i.S3Key,
			&i.ReportType,
			&i.Format,
			&i.GeneratedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
