// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: surveys.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMediaByJob = `-- name: CountMediaByJob :one
SELECT count(*) FROM survey_media WHERE job_id = $1
`

func (q *Queries) CountMediaByJob(ctx context.Context, jobID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaByJob, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChecklistTemplate = `-- name: CreateChecklistTemplate :one
INSERT INTO checklist_templates (name, survey_type, version, steps)
VALUES ($1, $2, $3, $4)
RETURNING id, name, survey_type, version, is_active, steps, created_at
`

type CreateChecklistTemplateParams struct {
	Name       string          `json:"name"`
	SurveyType string          `json:"survey_type"`
	Version    *int32          `json:"version"`
	Steps      json.RawMessage `json:"steps"`
}

func (q *Queries) CreateChecklistTemplate(ctx context.Context, arg CreateChecklistTemplateParams) (ChecklistTemplate, error) {
	row := q.db.QueryRow(ctx, createChecklistTemplate,
		arg.Name,
		arg.SurveyType,
		arg.Version,
		arg.Steps,
	)
	var i ChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SurveyType,
		&i.Version,
		&i.IsActive,
		&i.Steps,
		&i.CreatedAt,
	)
	return i, err
}

const createSurveyMedia = `-- name: CreateSurveyMedia :one
INSERT INTO survey_media (
    job_id, agent_id, step_id, media_type, s3_key, file_size_bytes, duration_sec,
    location, captured_at, file_hash_sha256, device_id, within_boundary
)
VALUES ($1, $2, $3, $4, $5, $6, $7, ST_SetSRID(ST_MakePoint($8, $9), 4326), $10, $11, $12, $13)
RETURNING id, job_id, agent_id, step_id, media_type, s3_key, file_size_bytes, duration_sec, location, captured_at, file_hash_sha256, device_id, within_boundary, duplicate_hash, uploaded_at
`

type CreateSurveyMediaParams struct {
	JobID          uuid.UUID   `json:"job_id"`
	AgentID        uuid.UUID   `json:"agent_id"`
	StepID         string      `json:"step_id"`
	MediaType      string      `json:"media_type"`
	S3Key          string      `json:"s3_key"`
	FileSizeBytes  *int64      `json:"file_size_bytes"`
	DurationSec    *int32      `json:"duration_sec"`
	StMakepoint    interface{} `json:"st_makepoint"`
	StMakepoint_2  interface{} `json:"st_makepoint_2"`
	CapturedAt     time.Time   `json:"captured_at"`
	FileHashSha256 string      `json:"file_hash_sha256"`
	DeviceID       *string     `json:"device_id"`
	WithinBoundary *bool       `json:"within_boundary"`
}

func (q *Queries) CreateSurveyMedia(ctx context.Context, arg CreateSurveyMediaParams) (SurveyMedium, error) {
	row := q.db.QueryRow(ctx, createSurveyMedia,
		arg.JobID,
		arg.AgentID,
		arg.StepID,
		arg.MediaType,
		arg.S3Key,
		arg.FileSizeBytes,
		arg.DurationSec,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.CapturedAt,
		arg.FileHashSha256,
		arg.DeviceID,
		arg.WithinBoundary,
	)
	var i SurveyMedium
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AgentID,
		&i.StepID,
		&i.MediaType,
		&i.S3Key,
		&i.FileSizeBytes,
		&i.DurationSec,
		&i.Location,
		&i.CapturedAt,
		&i.FileHashSha256,
		&i.DeviceID,
		&i.WithinBoundary,
		&i.DuplicateHash,
		&i.UploadedAt,
	)
	return i, err
}

const createSurveyResponse = `-- name: CreateSurveyResponse :one
INSERT INTO survey_responses (job_id, agent_id, template_id, responses, gps_trail, device_info, started_at, duration_minutes)
VALUES ($1, $2, $3, $4, ST_GeomFromGeoJSON($5), $6, $7, $8)
RETURNING id, job_id, agent_id, template_id, responses, gps_trail, device_info, started_at, submitted_at, duration_minutes
`

type CreateSurveyResponseParams struct {
	JobID             uuid.UUID          `json:"job_id"`
	AgentID           uuid.UUID          `json:"agent_id"`
	TemplateID        pgtype.UUID        `json:"template_id"`
	Responses         json.RawMessage    `json:"responses"`
	StGeomfromgeojson interface{}        `json:"st_geomfromgeojson"`
	DeviceInfo        []byte             `json:"device_info"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	DurationMinutes   *float32           `json:"duration_minutes"`
}

func (q *Queries) CreateSurveyResponse(ctx context.Context, arg CreateSurveyResponseParams) (SurveyResponse, error) {
	row := q.db.QueryRow(ctx, createSurveyResponse,
		arg.JobID,
		arg.AgentID,
		arg.TemplateID,
		arg.Responses,
		arg.StGeomfromgeojson,
		arg.DeviceInfo,
		arg.StartedAt,
		arg.DurationMinutes,
	)
	var i SurveyResponse
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AgentID,
		&i.TemplateID,
		&i.Responses,
		&i.GpsTrail,
		&i.DeviceInfo,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.DurationMinutes,
	)
	return i, err
}

const getActiveTemplate = `-- name: GetActiveTemplate :one
SELECT id, name, survey_type, version, is_active, steps, created_at FROM checklist_templates
WHERE survey_type = $1 AND is_active = TRUE
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetActiveTemplate(ctx context.Context, surveyType string) (ChecklistTemplate, error) {
	row := q.db.QueryRow(ctx, getActiveTemplate, surveyType)
	var i ChecklistTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SurveyType,
		&i.Version,
		&i.IsActive,
		&i.Steps,
		&i.CreatedAt,
	)
	return i, err
}

const getSurveyResponseByJob = `-- name: GetSurveyResponseByJob :one
SELECT id, job_id, agent_id, template_id, responses, gps_trail, device_info, started_at, submitted_at, duration_minutes FROM survey_responses WHERE job_id = $1
`

func (q *Queries) GetSurveyResponseByJob(ctx context.Context, jobID uuid.UUID) (SurveyResponse, error) {
	row := q.db.QueryRow(ctx, getSurveyResponseByJob, jobID)
	var i SurveyResponse
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AgentID,
		&i.TemplateID,
		&i.Responses,
		&i.GpsTrail,
		&i.DeviceInfo,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.DurationMinutes,
	)
	return i, err
}

const listDuplicateHashesForParcel = `-- name: ListDuplicateHashesForParcel :many
SELECT sm.file_hash_sha256, count(*) as hash_count
FROM survey_media sm
JOIN survey_jobs sj ON sm.job_id = sj.id
WHERE sj.parcel_id = $1
  AND sm.file_hash_sha256 != ''
GROUP BY sm.file_hash_sha256
HAVING count(*) > 1
`

type ListDuplicateHashesForParcelRow struct {
	FileHashSha256 string `json:"file_hash_sha256"`
	HashCount      int64  `json:"hash_count"`
}

func (q *Queries) ListDuplicateHashesForParcel(ctx context.Context, parcelID uuid.UUID) ([]ListDuplicateHashesForParcelRow, error) {
	rows, err := q.db.Query(ctx, listDuplicateHashesForParcel, parcelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateHashesForParcelRow{}
	for rows.Next() {
		var i ListDuplicateHashesForParcelRow
		if err := rows.Scan(&i.FileHashSha256, &i.HashCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByJob = `-- name: ListMediaByJob :many
SELECT id, job_id, agent_id, step_id, media_type, s3_key, file_size_bytes, duration_sec, location, captured_at, file_hash_sha256, device_id, within_boundary, duplicate_hash, uploaded_at FROM survey_media WHERE job_id = $1 ORDER BY captured_at
`

func (q *Queries) ListMediaByJob(ctx context.Context, jobID uuid.UUID) ([]SurveyMedium, error) {
	rows, err := q.db.Query(ctx, listMediaByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyMedium{}
	for rows.Next() {
		var i SurveyMedium
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AgentID,
			&i.StepID,
			&i.MediaType,
			&i.S3Key,
			&i.FileSizeBytes,
			&i.DurationSec,
			&i.Location,
			&i.CapturedAt,
			&i.FileHashSha256,
			&i.DeviceID,
			&i.WithinBoundary,
			&i.DuplicateHash,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, survey_type, version, is_active, steps, created_at FROM checklist_templates ORDER BY survey_type, version DESC
`

func (q *Queries) ListTemplates(ctx context.Context) ([]ChecklistTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChecklistTemplate{}
	for rows.Next() {
		var i ChecklistTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SurveyType,
			&i.Version,
			&i.IsActive,
			&i.Steps,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
