// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone, email, full_name, role, state_code, district_code, city, keycloak_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, phone, email, full_name, role, avatar_url, state_code, district_code, city, status, phone_verified, language, notification_prefs, keycloak_id, created_at, updated_at
`

type CreateUserParams struct {
	Phone        string  `json:"phone"`
	Email        *string `json:"email"`
	FullName     string  `json:"full_name"`
	Role         string  `json:"role"`
	StateCode    *string `json:"state_code"`
	DistrictCode *string `json:"district_code"`
	City         *string `json:"city"`
	KeycloakID   *string `json:"keycloak_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Phone,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.StateCode,
		arg.DistrictCode,
		arg.City,
		arg.KeycloakID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.StateCode,
		&i.DistrictCode,
		&i.City,
		&i.Status,
		&i.PhoneVerified,
		&i.Language,
		&i.NotificationPrefs,
		&i.KeycloakID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, email, full_name, role, avatar_url, state_code, district_code, city, status, phone_verified, language, notification_prefs, keycloak_id, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.StateCode,
		&i.DistrictCode,
		&i.City,
		&i.Status,
		&i.PhoneVerified,
		&i.Language,
		&i.NotificationPrefs,
		&i.KeycloakID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByKeycloakID = `-- name: GetUserByKeycloakID :one
SELECT id, phone, email, full_name, role, avatar_url, state_code, district_code, city, status, phone_verified, language, notification_prefs, keycloak_id, created_at, updated_at FROM users WHERE keycloak_id = $1
`

func (q *Queries) GetUserByKeycloakID(ctx context.Context, keycloakID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByKeycloakID, keycloakID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.StateCode,
		&i.DistrictCode,
		&i.City,
		&i.Status,
		&i.PhoneVerified,
		&i.Language,
		&i.NotificationPrefs,
		&i.KeycloakID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, email, full_name, role, avatar_url, state_code, district_code, city, status, phone_verified, language, notification_prefs, keycloak_id, created_at, updated_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.StateCode,
		&i.DistrictCode,
		&i.City,
		&i.Status,
		&i.PhoneVerified,
		&i.Language,
		&i.NotificationPrefs,
		&i.KeycloakID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, phone, email, full_name, role, avatar_url, state_code, district_code, city, status, phone_verified, language, notification_prefs, keycloak_id, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.AvatarUrl,
			&i.StateCode,
			&i.DistrictCode,
			&i.City,
			&i.Status,
			&i.PhoneVerified,
			&i.Language,
			&i.NotificationPrefs,
			&i.KeycloakID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = COALESCE($2, email),
    full_name = COALESCE($3, full_name),
    avatar_url = COALESCE($4, avatar_url),
    state_code = COALESCE($5, state_code),
    district_code = COALESCE($6, district_code),
    city = COALESCE($7, city),
    language = COALESCE($8, language),
    notification_prefs = COALESCE($9, notification_prefs),
    updated_at = NOW()
WHERE id = $1
RETURNING id, phone, email, full_name, role, avatar_url, state_code, district_code, city, status, phone_verified, language, notification_prefs, keycloak_id, created_at, updated_at
`

type UpdateUserParams struct {
	ID                uuid.UUID `json:"id"`
	Email             *string   `json:"email"`
	FullName          *string   `json:"full_name"`
	AvatarUrl         *string   `json:"avatar_url"`
	StateCode         *string   `json:"state_code"`
	DistrictCode      *string   `json:"district_code"`
	City              *string   `json:"city"`
	Language          *string   `json:"language"`
	NotificationPrefs []byte    `json:"notification_prefs"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.AvatarUrl,
		arg.StateCode,
		arg.DistrictCode,
		arg.City,
		arg.Language,
		arg.NotificationPrefs,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.StateCode,
		&i.DistrictCode,
		&i.City,
		&i.Status,
		&i.PhoneVerified,
		&i.Language,
		&i.NotificationPrefs,
		&i.KeycloakID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status *string   `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}
